sudo: false
language: python
python:
 - 2.6
 - 2.7
 - 3.3
 - 3.6
matrix:
  allow_failures:
  - python: 2.6
install:
- pip install tox "setuptools>=28.2"
script:
- tox
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
    python: 3.6
  user: jaraco
  # supply password with `travis encrypt --add deploy.password`
  distributions: dists
  skip_upload_docs: true
